# Poricom
# Copyright (C) `2021-2022` `<Alarcon Ace Belen>`
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Lists
IMAGE_EXTENSIONS = [ "*.bmp", "*.gif", "*.jpg", "*.jpeg", "*.png", "*.pbm", "*.pgm", "*.ppm", "*.webp", "*.xbm", "*.xpm",]
LANGUAGE = [ " Japanese", " Korean", " Chinese SIM", " Chinese TRA  ", " English",]
ORIENTATION = [ " Vertical", " Horizontal",]
FONT_STYLE = [ " Poppins", " Arial", " Verdana", " Helvetica", " Times New Roman",]
FONT_SIZE = [ " 12", " 14", " 16", " 20", " 24", " 32", " 40", " 56", " 72",]
IMAGE_SCALING= [ " Fit to Width", " Fit to Height", " Fit to Screen",]
MODIFIER = [ " Ctrl", " Shift", " Alt", " Ctrl+Alt", " Shift+Alt", " Shift+Ctrl", " Shift+Alt+Ctrl", " No Modifier"]

# Filepath
STYLES_PATH = "./assets/"
NAV_ROOT = "./assets/images/"
TBAR_ICONS = "./assets/images/icons/"
TBAR_ICONS_LIGHT = "./assets/images/icons/"
LANG_PATH = "./assets/languages/"

STYLES_DEFAULT = "./assets/styles.qss"
LOGO = "./assets/images/icons/logo.ico"
HOME_IMAGE = "./assets/images/home.png"
ABOUT_IMAGE = "./assets/images/about.png"
TBAR_ICON_DEFAULT = "./assets/images/icons/default_icon.png"

# Sizes
RBN_HEIGHT = 2.4
TBAR_ISIZE_REL = 0.1
TBAR_ISIZE_MARGIN = 1.3
NAV_VIEW_RATIO = [ 3, 11,]

# Mode
VIEW_IMAGE_MODE = 0
SPLIT_VIEW_MODE = false

[SELECTED_INDEX]
language = 0
orientation = 0
font_style = 0
font_size = 2
image_scaling = 0
modifier = 2

[PICKER_INDEX]
language = 49
orientation = 50
font_style = 51
font_size = 52
image_scaling = 53
modifier = 54

[SHORTCUT]
capture_external = "Alt+Q"
capture_external_key = "Q"
capture_external_tip = "This will minimize the app and perform OCR on the current screen. Alternatively, you may use the shortcut: "

[NAV_FUNCS]
path_changed = "view_image_from_fdialog"
nav_clicked = "view_image_from_explorer"

# Ribbon buttons (always on)
[MODE_FUNCS]

  [MODE_FUNCS.zoom_in]
  help_title = "Zoom in"
  help_msg = "Hint: Double click the image to reset zoom."
  path = "zoom_in.png"
  toggle = false
  align = "AlignRight"
  icon_h = 0.45
  icon_w = 0.45

  [MODE_FUNCS.zoom_out]
  help_title = "Zoom out"
  help_msg = "Hint: Double click the image to reset zoom."
  path = "zoom_out.png"
  toggle = false
  align = "AlignRight"
  icon_h = 0.45
  icon_w = 0.45

  [MODE_FUNCS.load_image_at_idx]
  help_title = ""
  help_msg = "Jump to page"
  path = "load_image_at_idx.png"
  toggle = false
  align = "AlignRight"
  icon_h = 0.45
  icon_w = 1.3

  [MODE_FUNCS.load_prev_image]
  help_title = ""
  help_msg = "Show previous image"
  path = "load_prev_image.png"
  toggle = false
  align = "AlignRight"
  icon_h = 0.45
  icon_w = 0.6

  [MODE_FUNCS.load_next_image]
  help_title = ""
  help_msg = "Show next image"
  path = "load_next_image.png"
  toggle = false
  align = "AlignRight"
  icon_h = 0.45
  icon_w = 0.6

# Ribbon buttons
[TBAR_FUNCS]

  [TBAR_FUNCS.FILE]

    [TBAR_FUNCS.FILE.open_dir]
    help_title = "Open manga directory"
    help_msg = "Open a directory containing images."
    path = "open_dir.png"
    toggle = false
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

    [TBAR_FUNCS.FILE.open_manga]
    help_title = "Open manga file"
    help_msg = "Supports the following formats: cbr, cbz, pdf."
    path = "open_manga.png"
    toggle = false
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

    [TBAR_FUNCS.FILE.capture_external_helper]
    help_title = "External capture"
    help_msg = "This will minimize the app and perform OCR on the current screen. Alternatively, you may use the shortcut Alt+Q."
    path = "capture_external_helper.png"
    toggle = false
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

  [TBAR_FUNCS.VIEW]

    [TBAR_FUNCS.VIEW.toggle_stylesheet]
    help_title = "Change theme"
    help_msg = "Switch between light and dark mode."
    path = "toggle_stylesheet.png"
    toggle = false
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

    [TBAR_FUNCS.VIEW.modify_font_settings]
    help_title = "Modify preview text"
    help_msg = "Change font style and font size of preview text."
    path = "modify_font_settings.png"
    toggle = false
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

    [TBAR_FUNCS.VIEW.toggle_split_view]
    help_title = "Turn on split view"
    help_msg = "View two images at once."
    path = "toggle_split_view.png"
    toggle = true
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

    [TBAR_FUNCS.VIEW.scale_image]
    help_title = "Adjust image scaling"
    help_msg = "Fit an image according to the available options: fit to width, fit to height, fit to screen"
    path = "scale_image.png"
    toggle = false
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

  [TBAR_FUNCS.CONTROLS]

    [TBAR_FUNCS.CONTROLS.toggle_mouse_mode]
    help_title = "Change mouse behavior"
    help_msg = "This will disable text detection. Turn this on only if do not want to hold CTRL key to zoom and pan on an image."
    path = "toggle_mouse_mode.png"
    toggle = true
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

    [TBAR_FUNCS.CONTROLS.modify_hotkeys]
    help_title = "Remap hotkeys"
    help_msg = "Change shortcut for external captures."
    path = "modify_hotkeys.png"
    toggle = false
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

  [TBAR_FUNCS.MISC]

    [TBAR_FUNCS.MISC.load_model]
    help_title = "Switch detection model"
    help_msg = "Switch between MangaOCR and Tesseract models."
    path = "load_model.png"
    toggle = true
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

    [TBAR_FUNCS.MISC.modify_tesseract]
    help_title = "Tesseract settings"
    help_msg = "Set the language and orientation for the Tesseract model."
    path = "modify_tesseract.png"
    toggle = false
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0

    [TBAR_FUNCS.MISC.toggle_logging]
    help_title = "Enable text logging"
    help_msg = "Save detected text to a text file located in the current project directory."
    path = "toggle_logging.png"
    toggle = true
    align = "AlignLeft"
    icon_h = 1.0
    icon_w = 1.0
